version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=AnishJoshi1999
      - MONGO_URI=mongodb+srv://anishjoshi1999:PnwA9TYDA86mxcKz@hamrokhabar.hsnjsu1.mongodb.net/TRY
    ports:
      - '3000:3000'
